import type { Metadata } from "next";
import { Suspense } from "react";
import { SearchProvider } from "@/providers/SearchProvider";
import "../globals.css";

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: "Nest playground",
  description: "Generated by @MagisterUnivers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ background: 'white' }}
      >
        <Suspense>
          <SearchProvider>
            {children}
          </SearchProvider>
        </Suspense>
      </body>
    </html>
  );
}
